<?php
return [
    'form' => [
        'w-full max-w-xl mx-auto p-8 bg-white rounded-lg shadow-lg space-y-8',
        'bg-gray-100 p-6 rounded-lg max-w-2xl mx-auto space-y-4',
        'container mx-auto px-4 py-8 bg-white sm:px-6 lg:px-8 space-y-6',
        'max-w-md mx-auto mt-10 bg-white p-6 rounded shadow-md',
        'w-full max-w-lg mx-auto p-10 bg-white rounded-lg border border-gray-200',
        'mx-auto w-full px-6 py-8 bg-white shadow-sm rounded-lg',
        'relative w-full max-w-3xl mx-auto p-12 bg-white rounded-xl shadow-xl',
        'flex flex-col w-full max-w-lg mx-auto gap-4 p-6 bg-white rounded-md shadow-md',
        'w-full max-w-2xl mx-auto p-8 bg-white border border-gray-100 rounded-lg',
        'grid grid-cols-1 gap-6 w-full max-w-lg mx-auto p-6 bg-white rounded-lg',
    ],

    'label' => [
        'block text-sm font-semibold text-gray-700 mb-2',
        'inline-block text-sm font-medium text-gray-600 mb-1',
        'block text-base font-medium text-gray-800 mb-1',
        'uppercase text-xs font-medium text-gray-500 mb-1',
        'block text-sm font-normal text-gray-900 mb-2',
        'block text-sm font-semibold text-indigo-600 mb-1',
        'block text-sm font-semibold text-blue-700 mb-1',
        'block text-sm font-medium text-green-700 mb-1',
        'block text-sm font-medium text-red-600 mb-1',
        'block text-sm font-medium text-yellow-700 mb-1',
    ],

    'input-text' => [
        'block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500',
        'block w-full px-3 py-2 border border-gray-200 rounded-lg placeholder-gray-400 focus:ring focus:ring-indigo-300',
        'w-full p-2 border border-gray-300 rounded focus:border-blue-400 focus:outline-none',
        'block w-full py-2 px-3 bg-white border border-gray-300 rounded-md text-gray-900 placeholder-gray-500',
        'block w-full px-4 py-2 text-base border border-gray-400 rounded-lg focus:ring-2 focus:ring-green-400',
        'w-full px-3 py-2 border border-gray-300 rounded-lg shadow focus:ring focus:ring-purple-200',
        'block w-full pl-3 pr-10 py-2 border-gray-300 rounded-md focus:outline-none focus:border-indigo-500',
        'w-full px-4 py-2 border border-gray-300 rounded-full focus:ring-2 focus:ring-blue-300',
        'block w-full px-3 py-2 border-b border-gray-300 focus:border-blue-500 focus:outline-none',
        'w-full px-4 py-2 bg-gray-50 border border-gray-300 rounded-md focus:ring focus:ring-gray-200',
    ],

    'input-checkbox' => [
        'h-4 w-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500',
        'form-checkbox h-5 w-5 text-green-600 border-gray-300 rounded focus:ring focus:ring-green-200',
        'h-4 w-4 text-red-600 rounded border-gray-300 focus:ring-red-500',
        'h-6 w-6 text-indigo-600 border-gray-300 rounded focus:ring-indigo-200',
        'appearance-none h-4 w-4 border border-gray-300 rounded-sm checked:bg-blue-600 focus:outline-none',
        'h-4 w-4 text-yellow-500 border-gray-300 rounded focus:ring-yellow-200',
        'h-5 w-5 text-purple-600 border-gray-300 rounded focus:ring-purple-200',
        'h-4 w-4 text-gray-700 border-gray-400 rounded focus:ring focus:ring-gray-200',
        'form-checkbox h-4 w-4 text-pink-600 border-gray-300 rounded focus:ring-pink-200',
        'h-4 w-4 border border-gray-300 rounded focus:ring focus:ring-indigo-500',
    ],

    'input-radio' => [
        'form-radio h-4 w-4 text-blue-600 border-gray-300 focus:ring-blue-500',
        'h-5 w-5 text-green-600 border-gray-300 rounded-full focus:ring focus:ring-green-200',
        'form-radio h-4 w-4 text-red-600 border-gray-300 focus:ring-red-200',
        'h-4 w-4 text-indigo-600 border-gray-300 focus:ring-indigo-200',
        'h-4 w-4 text-yellow-500 border-gray-300 focus:ring-yellow-200',
        'h-4 w-4 text-purple-600 border-gray-300 focus:ring-purple-200',
        'form-radio h-4 w-4 text-pink-600 border-gray-300 focus:ring-pink-200',
        'h-4 w-4 text-gray-700 border-gray-300 focus:ring focus:ring-gray-200',
        'h-4 w-4 text-blue-500 border-gray-300 focus:ring focus:ring-blue-300',
        'h-4 w-4 text-green-500 border-gray-300 focus:ring focus:ring-green-300',
    ],

    'select-box' => [
        'block w-full px-4 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500',
        'block w-full px-3 py-2 bg-gray-50 border border-gray-400 rounded-lg focus:border-indigo-500',
        'w-full p-2 border border-gray-300 rounded focus:ring focus:ring-indigo-200',
        'block w-full px-4 py-2 bg-white border border-gray-200 rounded-lg focus:outline-none',
        'block w-full px-3 py-2 bg-white border border-gray-300 rounded-md text-gray-900',
        'block w-full px-4 py-2 bg-gray-100 border border-gray-300 rounded focus:border-green-500',
        'w-full px-3 py-2 border border-gray-300 rounded shadow-sm focus:ring focus:ring-purple-200',
        'block w-full px-4 py-2 bg-white border border-red-300 rounded-md focus:ring-red-200',
        'block w-full px-3 py-2 bg-white border border-green-300 rounded-lg focus:ring-green-200',
        'block w-full px-4 py-2 bg-white border border-blue-300 rounded focus:border-blue-500',
    ],

    'textarea' => [
        'block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-200',
        'block w-full p-2 bg-gray-50 border border-gray-200 rounded-lg placeholder-gray-500 focus:ring focus:ring-indigo-300',
        'w-full px-3 py-2 border border-gray-300 rounded focus:border-green-400',
        'block w-full px-4 py-2 bg-white border border-gray-300 rounded-md text-gray-900',
        'block w-full px-3 py-2 border border-gray-400 rounded-lg focus:ring focus:ring-green-300',
        'w-full px-4 py-2 border border-gray-300 rounded shadow focus:ring focus:ring-purple-200',
        'block w-full pl-3 pr-10 py-2 border-gray-300 rounded-md focus:outline-none',
        'w-full px-4 py-2 bg-gray-50 border border-gray-300 rounded-md focus:ring focus:ring-gray-200',
        'block w-full px-3 py-2 bg-white border border-red-300 rounded-md focus:ring focus:ring-red-200',
        'block w-full px-4 py-2 bg-white border border-blue-300 rounded focus:border-blue-500',
    ],

    'fieldset' => [
        'border border-gray-300 p-4 rounded-md bg-gray-50',
        'border-2 border-dashed border-gray-200 p-4 rounded-lg',
        'p-4 bg-white border-t-4 border-blue-500 rounded',
        'p-4 bg-white shadow-inner rounded-lg',
        'p-6 bg-gray-100 border border-gray-300 rounded',
        'p-4 bg-white border border-green-300 rounded-md',
        'p-5 bg-white border border-red-300 rounded-lg',
        'p-4 bg-gray-50 border border-gray-200 rounded-lg',
        'p-4 bg-white border-l-4 border-indigo-600 rounded',
        'p-4 bg-white border-r-4 border-yellow-400 rounded',
    ],

    'legend' => [
        'font-semibold text-lg text-gray-800 mb-2',
        'font-bold text-xl text-indigo-600 mb-3',
        'font-medium text-base text-gray-700 mb-2',
        'uppercase text-sm text-gray-500 mb-2',
        'text-lg font-semibold text-blue-700 mb-2',
        'text-md font-medium text-green-700 mb-2',
        'text-base font-semibold text-red-600 mb-2',
        'text-sm font-bold text-gray-600 mb-2',
        'text-lg font-semibold text-yellow-700 mb-2',
        'text-lg font-semibold text-purple-700 mb-2',
    ],

    'submitbutton' => [
        'w-full bg-blue-600 text-white px-4 py-2 rounded-md shadow hover:bg-blue-700 transition duration-150',
        'w-full bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-green-600',
        'w-full bg-indigo-600 text-white py-3 rounded-full hover:bg-indigo-700',
        'block w-full bg-red-500 text-white px-5 py-2 rounded-md hover:bg-red-600',
        'w-full bg-yellow-400 text-gray-800 px-4 py-2 rounded hover:bg-yellow-500',
        'w-full bg-purple-600 text-white px-4 py-2 rounded-md hover:bg-purple-700',
        'w-full bg-teal-500 text-white px-4 py-2 rounded-md hover:bg-teal-600',
        'w-full bg-pink-500 text-white px-4 py-2 rounded-md hover:bg-pink-600',
        'w-full bg-gray-800 text-white px-4 py-2 rounded-md hover:bg-gray-900',
        'w-full bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 transition ease-in-out',
    ],

    'button-add' => [
        'bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded transition',
        'bg-green-500 hover:bg-green-600 text-white px-3 py-1 rounded-full',
        'bg-yellow-400 hover:bg-yellow-500 text-white px-3 py-1 rounded-md',
        'bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg',
        'bg-red-500 hover:bg-red-600 text-white px-2 py-1 rounded',
        'bg-indigo-500 hover:bg-indigo-600 text-white px-3 py-1 rounded-md',
        'bg-teal-500 hover:bg-teal-600 text-white px-3 py-2 rounded',
        'bg-pink-500 hover:bg-pink-600 text-white px-4 py-2 rounded-md',
        'bg-gray-600 hover:bg-gray-700 text-white px-2 py-1 rounded',
        'bg-blue-500 hover:bg-blue-600 text-white px-4 py-1 rounded-md',
    ],

    'error-text' => [
        'text-red-600 text-sm mt-1',
        'text-red-500 text-xs mt-1',
        'text-red-700 text-sm mt-2',
        'text-red-600 text-sm italic',
        'text-red-500 text-sm underline',
        'text-red-600 text-sm font-medium',
        'text-red-700 text-sm uppercase',
        'text-red-600 text-xs',
        'text-red-500 text-xs italic',
        'text-red-700 text-xs font-semibold',
    ],
];
